domains:
  P1:
    name: "Moral/Formative"
    rank: 1
    dimensions:
      P1-1:
        name: "Holiness"
        rank: 1
      P1-2:
        name: "Justice"
        rank: 2

  P2:
    name: "Sustaining/Existential"
    rank: 2
    dimensions:
      P2-1:
        name: "Preservation"
        rank: 1

  P3:
    name: "Relational/Formal"
    rank: 3
    dimensions:
      P3-1:
        name: "Fidelity"
        rank: 1